In [2]:
from numpy import *
from numpy.linalg import *

In [3]:
A = array([[-25, 35, -65],[-45, 45, -85], [-15, 5, -15]])

In [4]:
v1 = array([[1],[2],[1]])
v2 = array([[-1],[1],[1]])
v3 = array([[-3], [-2], [1]])

In [5]:
print(eigvals(A))

[-20.   5.  20.]


In [23]:
L = [-5, -1, 2]
A = diag(L)
print(A)


[[-5  0  0]
 [ 0 -1  0]
 [ 0  0  2]]


In [60]:
A = array([[2,-2],[2,-3]])
D = array([[1,0],[0,-2]])


In [89]:
P = array([[-2,2],[-1,4]])
print(A@P)
print(P@D)

[[-2 -4]
 [-1 -8]]
[[-2 -4]
 [-1 -8]]


In [90]:
A = array([[3,-2],[4,-3]])

In [91]:
print(eigvals(A))

[ 1. -1.]


In [104]:
B = array([[2,-2],[4,-4]])
null = array([[0],[0]])

0.0


In [105]:
print(B," = ", null)

[[ 2 -2]
 [ 4 -4]]  =  [[0]
 [0]]


In [138]:
t = 1
B = array([[4,-2],[4,-2]])
C = array([[t, 1/2*t],[t, t]])

In [151]:
print(inv(C)@B@C)
print(B**15)

[[2. 0.]
 [0. 0.]]
[[1073741824     -32768]
 [1073741824     -32768]]


In [114]:
inv(A)

array([[ 3., -2.],
       [ 4., -3.]])

In [6]:
A = array([[-9,6,12],[-14,11,14],[1,-1,2]])

In [7]:
print(eigvals(A))

[-3.  3.  4.]


In [8]:
print(eig(array([[5,2],[-4,-1]])))

(array([3., 1.]), array([[ 0.70710678, -0.4472136 ],
       [-0.70710678,  0.89442719]]))


0.5773502691896258